kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zookeeper-standalone
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-standalone
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-standalone
  local:
    path: /mnt/data/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: zookeeper-standalone
#   namespace: kafka
# spec:
#   storageClassName: zookeeper-standalone
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 512Mi
# ---

