apiVersion: apps/v1
kind: Deployment
metadata:
  name: springjms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springjms
  template:
    metadata:
      name: springjms
      labels:
        app: springjms
    spec:
      containers:
        - image: csgear/springjms:1.0.0
          name: springboot