---
kind: Service
apiVersion: v1
metadata:
  namespace: rocketmq
  name: service-rocketmq-namesrv-prod
  labels:
    app: service-rocketmq-namesrv-prod
spec:
  ports:
    - protocol: TCP
      port: 9876
      targetPort: 9876
  selector:
    app: pod-rocketmq-namesrv-prod
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: rocketmq
  name: statefulset-rocketmq-namesrv-prod
  labels:
    app: statefulset-rocketmq-namesrv-prod
spec:
  replicas: 1
  serviceName: service-rocketmq-namesrv-prod
  selector:
    matchLabels:
      app: pod-rocketmq-namesrv-prod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-namesrv-prod
    spec:
      containers:
        - image: csgear/rocketmq-namesrv:4.5.1
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          name: container-rocketmq-namesrv-prod
          ports:
            - protocol: TCP
              containerPort: 9876
          resources:
            requests:
              cpu: "0.25"
              memory: 512Mi
            limits:
              cpu: "0.5"
              memory: 2048Mi

          readinessProbe:
            tcpSocket:
              port: 9876
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 9876
            initialDelaySeconds: 120
            periodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pod-rocketmq-namesrv-prod
                topologyKey: kubernetes.io/hostname
      dnsPolicy: ClusterFirst
      restartPolicy: Always
