version: "2.1"

services:
  # product:
  #   build: microservices/product-service
  #   mem_limit: 350m
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   depends_on:
  #     - mongodb

  # recommendation:
  #   build: microservices/recommendation-service
  #   mem_limit: 350m
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   depends_on:
  #     - mongodb

  # review:
  #   build: microservices/review-service
  #   mem_limit: 350m
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # product-composite:
  #   build: microservices/product-composite-service
  #   mem_limit: 350m
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker

  # $ mongo
  mongodb:
    image: mongo:4.2
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-umysql", "-pmysql", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
