kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-standalone
  namespace: mongodb
spec:
  storageClassName: mongodb-standalone
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Mi
---