---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  # echo -n "my-root-secret-password" | base64
  ROOT_PASSWORD: bXktcm9vdC1zZWNyZXQtcGFzc3dvcmQ=
  MYSQL_USER: bXlzcWw=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
