apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: springjms.local
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: springjms-cluster-ip-service
              servicePort: 8080
