version: '2'
services:
  namesrv:
    image: csgear/rocketmq-namesrv:4.5.1
    container_name: rmqnamesrv_vkemall
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/opt/rocketmq/logs
  broker:
    image: csgear/rocketmq-broker:4.5.1
    container_name: rmqbroker_vkemall
    environment:  
      NAMESRV_ADDR: "namesrv:9876"
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/broker/logs:/opt/rocketmq/logs
      - ./data/broker/store:/opt/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq/rocketmq-4.5.1/conf/broker.conf
    depends_on:
      - namesrv
